feat: yamllint

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -3,11 +3,10 @@ name: 'CI: Build, test, and push'
 on:
   push:
     branches:
-      - main 
-  
+      - main
   pull_request:
     branches:
-      - main  
+      - main
 
 env:
   PROJECT_ID: go-kickstart
@@ -21,109 +20,109 @@ jobs:
     runs-on: 'ubuntu-latest'
     steps:
 
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - uses: actions/setup-go@v5
-      with:
-        go-version: stable
+      - uses: actions/setup-go@v5
+        with:
+          go-version: stable
 
-    - name: Run yaml lint
-      run: |-
-        sudo apt-get install -y yamllint
-        make lint-yaml
+      - name: Run yaml lint
+        run: |-
+          sudo apt-get install -y yamllint
+          make lint-yaml
 
-    - name: Run Go lint
-      uses: golangci/golangci-lint-action@v8
-      with:
-        version: v2.1
+      - name: Run Go lint
+        uses: golangci/golangci-lint-action@v8
+        with:
+          version: v2.1
 
   test:
     runs-on: 'ubuntu-latest'
     steps:
 
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - uses: actions/setup-go@v5
-      with:
-        go-version: stable
+      - uses: actions/setup-go@v5
+        with:
+          go-version: stable
 
-    - name: Get PR ID
-      id: pr_num
-      if: github.event_name == 'pull_request'
-      run: |-
-        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
-        echo "PR number is ${PR_NUMBER}"
-        echo "PR_NUMBER=${PR_NUMBER}" >> "${GITHUB_ENV}"
+      - name: Get PR ID
+        id: pr_num
+        if: github.event_name == 'pull_request'
+        run: |-
+          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+          echo "PR number is ${PR_NUMBER}"
+          echo "PR_NUMBER=${PR_NUMBER}" >> "${GITHUB_ENV}"
 
-    - name: Set up gotestfmt
-      uses: GoTestTools/gotestfmt-action@v2
+      - name: Set up gotestfmt
+        uses: GoTestTools/gotestfmt-action@v2
 
-    - name: Run unit test
-      id: ut
-      continue-on-error: true
-      run: GO_TEST_ARGS=-json make test | tee /tmp/gotest.log | gotestfmt
+      - name: Run unit test
+        id: ut
+        continue-on-error: true
+        run: GO_TEST_ARGS=-json make test | tee /tmp/gotest.log | gotestfmt
 
-    - name: Comment to PR
-      if: github.event_name == 'pull_request'
-      uses: peter-evans/create-or-update-comment@v4
-      with:
-        issue-number: ${{env.PR_NUMBER}}
-        body-path: /tmp/gotest.log
+      - name: Comment to PR
+        if: github.event_name == 'pull_request'
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          issue-number: ${{env.PR_NUMBER}}
+          body-path: /tmp/gotest.log
 
-    - name: check test coverage
-      id: coverage
-      uses: vladopajic/go-test-coverage@v2
-      with:
-        config: ./.testcoverage.yml
+      - name: check test coverage
+        id: coverage
+        uses: vladopajic/go-test-coverage@v2
+        with:
+          config: ./.testcoverage.yml
 
-    - name: Comment to PR
-      if: github.event_name == 'pull_request'
-      uses: peter-evans/create-or-update-comment@v4
-      with:
-        issue-number: ${{env.PR_NUMBER}}
-        body: |
-          go-test-coverage report:
-          ```
-          ${{ fromJSON(steps.coverage.outputs.report) }}```
+      - name: Comment to PR
+        if: github.event_name == 'pull_request'
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          issue-number: ${{env.PR_NUMBER}}
+          body: |
+            go-test-coverage report:
+            ```
+            ${{ fromJSON(steps.coverage.outputs.report) }}```
 
-    - name: Check coverage
-      if: steps.coverage.outcome == 'failure' || steps.ut.outcome == 'failure'
-      shell: bash
-      run: echo "Unit test or coverage check failed" && exit 1
+      - name: Check coverage
+        if: steps.coverage.outcome == 'failure' || steps.ut.outcome == 'failure'
+        shell: bash
+        run: echo "Unit test or coverage check failed" && exit 1
 
   govulncheck:
     runs-on: 'ubuntu-latest'
     steps:
 
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - uses: actions/setup-go@v5
-      with:
-        go-version: stable
+      - uses: actions/setup-go@v5
+        with:
+          go-version: stable
 
-    - name: Install vulncheck and run
-      continue-on-error: true
-      run: |-
-        go install golang.org/x/vuln/cmd/govulncheck@latest
-        make vulncheck | tee /tmp/govulncheck.log
+      - name: Install vulncheck and run
+        continue-on-error: true
+        run: |-
+          go install golang.org/x/vuln/cmd/govulncheck@latest
+          make vulncheck | tee /tmp/govulncheck.log
 
-    - name: Get PR ID
-      id: pr_num
-      if: github.event_name == 'pull_request'
-      run: |-
-        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
-        echo "PR number is ${PR_NUMBER}"
-        echo "PR_NUMBER=${PR_NUMBER}" >> "${GITHUB_ENV}"
+      - name: Get PR ID
+        id: pr_num
+        if: github.event_name == 'pull_request'
+        run: |-
+          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
+          echo "PR number is ${PR_NUMBER}"
+          echo "PR_NUMBER=${PR_NUMBER}" >> "${GITHUB_ENV}"
 
-    - name: Comment to PR
-      if: github.event_name == 'pull_request'
-      uses: peter-evans/create-or-update-comment@v4
-      with:
-        issue-number: ${{env.PR_NUMBER}}
-        body-path: /tmp/govulncheck.log
+      - name: Comment to PR
+        if: github.event_name == 'pull_request'
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          issue-number: ${{env.PR_NUMBER}}
+          body-path: /tmp/govulncheck.log
 
   image:
     runs-on: 'ubuntu-latest'
@@ -135,21 +134,21 @@ jobs:
 
     steps:
 
-    - id: gcp_auth
-      name: Authenticate to Google Cloud
-      uses: google-github-actions/auth@v2
-      with:
-        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
+      - id: gcp_auth
+        name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@v2
+        with:
+          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
 
-    - name: Docker Auth
-      uses: docker/login-action@v3
-      with:
-        username: oauth2accesstoken
-        password: ${{ steps.gcp_auth.outputs.auth_token }}
-        registry: ${{ env.REGION }}-docker.pkg.dev
+      - name: Docker Auth
+        uses: docker/login-action@v3
+        with:
+          username: oauth2accesstoken
+          password: ${{ steps.gcp_auth.outputs.auth_token }}
+          registry: ${{ env.REGION }}-docker.pkg.dev
 
-    - name: Build and Push Container
-      run: |-
-        DOCKER_TAG="$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}:${{ github.sha }}"
-        docker build --tag "${DOCKER_TAG}" .
-        docker push "${DOCKER_TAG}"
+      - name: Build and Push Container
+        run: |-
+          DOCKER_TAG="$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}:${{ github.sha }}"
+          docker build --tag "${DOCKER_TAG}" .
+          docker push "${DOCKER_TAG}"
